---

#############
# Install Kops
#############

- name: Download Kops binaries
  get_url:
    url: "{{ kops_download_path }}"
    dest: /usr/local/bin/kops_crist
    owner: root
    group: root
    mode: 0755
    force: yes
  when: ansible_os_family == 'Debian'
  become: true
