---

- name: Copying deployment file to server
  copy:
    src: ./deployment/consumer_deployment.yaml
    dest: /tmp/consumer_deployment.yaml
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Deploying Consumer using kubectl
  shell: "kubectl apply -f /tmp/consumer_deployment.yaml"

